//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDCrudTestGloboMarketEntities : DbContext
    {
        public BDCrudTestGloboMarketEntities()
            : base("name=BDCrudTestGloboMarketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<sub_categoria> sub_categoria { get; set; }
    
        public virtual int Usp_Delete_Categoria(Nullable<long> id_categ)
        {
            var id_categParameter = id_categ.HasValue ?
                new ObjectParameter("id_categ", id_categ) :
                new ObjectParameter("id_categ", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Usp_Delete_Categoria", id_categParameter);
        }
    
        public virtual int Usp_Delete_Sub_Categoria(Nullable<long> id_subcateg)
        {
            var id_subcategParameter = id_subcateg.HasValue ?
                new ObjectParameter("id_subcateg", id_subcateg) :
                new ObjectParameter("id_subcateg", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Usp_Delete_Sub_Categoria", id_subcategParameter);
        }
    
        public virtual int Usp_Ins_Categoria(Nullable<long> id_categ, string nombre_categ, string descrip_categ)
        {
            var id_categParameter = id_categ.HasValue ?
                new ObjectParameter("id_categ", id_categ) :
                new ObjectParameter("id_categ", typeof(long));
    
            var nombre_categParameter = nombre_categ != null ?
                new ObjectParameter("nombre_categ", nombre_categ) :
                new ObjectParameter("nombre_categ", typeof(string));
    
            var descrip_categParameter = descrip_categ != null ?
                new ObjectParameter("descrip_categ", descrip_categ) :
                new ObjectParameter("descrip_categ", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Usp_Ins_Categoria", id_categParameter, nombre_categParameter, descrip_categParameter);
        }
    
        public virtual int Usp_Ins_Sub_Categoria(Nullable<long> id_subcateg, string nombre_subCat, string descrip_subCat)
        {
            var id_subcategParameter = id_subcateg.HasValue ?
                new ObjectParameter("id_subcateg", id_subcateg) :
                new ObjectParameter("id_subcateg", typeof(long));
    
            var nombre_subCatParameter = nombre_subCat != null ?
                new ObjectParameter("nombre_subCat", nombre_subCat) :
                new ObjectParameter("nombre_subCat", typeof(string));
    
            var descrip_subCatParameter = descrip_subCat != null ?
                new ObjectParameter("descrip_subCat", descrip_subCat) :
                new ObjectParameter("descrip_subCat", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Usp_Ins_Sub_Categoria", id_subcategParameter, nombre_subCatParameter, descrip_subCatParameter);
        }
    
        public virtual ObjectResult<Usp_Sel_All_Product_Result> Usp_Sel_All_Product()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Sel_All_Product_Result>("Usp_Sel_All_Product");
        }
    
        public virtual ObjectResult<Usp_Sel_Categ_Disponibles_Result> Usp_Sel_Categ_Disponibles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Sel_Categ_Disponibles_Result>("Usp_Sel_Categ_Disponibles");
        }
    
        public virtual ObjectResult<string> Usp_Sel_Prod_Brand()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Usp_Sel_Prod_Brand");
        }
    
        public virtual ObjectResult<Nullable<decimal>> Usp_Sel_Prod_Prices()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Usp_Sel_Prod_Prices");
        }
    
        public virtual ObjectResult<string> Usp_Sel_Prod_Supplier()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Usp_Sel_Prod_Supplier");
        }
    
        public virtual ObjectResult<Usp_Sel_Sub_Categ_Disponibles_Result> Usp_Sel_Sub_Categ_Disponibles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Sel_Sub_Categ_Disponibles_Result>("Usp_Sel_Sub_Categ_Disponibles");
        }
    
        public virtual int Usp_Update_Categoria(Nullable<long> id_categ, string nombre_categ, string descrip_categ)
        {
            var id_categParameter = id_categ.HasValue ?
                new ObjectParameter("id_categ", id_categ) :
                new ObjectParameter("id_categ", typeof(long));
    
            var nombre_categParameter = nombre_categ != null ?
                new ObjectParameter("nombre_categ", nombre_categ) :
                new ObjectParameter("nombre_categ", typeof(string));
    
            var descrip_categParameter = descrip_categ != null ?
                new ObjectParameter("descrip_categ", descrip_categ) :
                new ObjectParameter("descrip_categ", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Usp_Update_Categoria", id_categParameter, nombre_categParameter, descrip_categParameter);
        }
    
        public virtual int Usp_Update_Sub_Categoria(Nullable<long> id_subcateg, string nombre_subCatg, string descrip_subCat)
        {
            var id_subcategParameter = id_subcateg.HasValue ?
                new ObjectParameter("id_subcateg", id_subcateg) :
                new ObjectParameter("id_subcateg", typeof(long));
    
            var nombre_subCatgParameter = nombre_subCatg != null ?
                new ObjectParameter("nombre_subCatg", nombre_subCatg) :
                new ObjectParameter("nombre_subCatg", typeof(string));
    
            var descrip_subCatParameter = descrip_subCat != null ?
                new ObjectParameter("descrip_subCat", descrip_subCat) :
                new ObjectParameter("descrip_subCat", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Usp_Update_Sub_Categoria", id_subcategParameter, nombre_subCatgParameter, descrip_subCatParameter);
        }
    }
}
