//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        public long id_prod { get; set; }
        public string nombre_prod { get; set; }
        public string descrip_prod { get; set; }
        public string product_image { get; set; }
        public decimal precio_prod { get; set; }
        public decimal desc_product { get; set; }
        public long cantidad_stock { get; set; }
        public string unidad_de_medida_peso { get; set; }
        public double peso_prod { get; set; }
        public double volumen_prod { get; set; }
        public bool estado { get; set; }
        public string proveedor { get; set; }
        public string marca { get; set; }
    }
}
