//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sub_categoria
    {
        public long id_subcateg { get; set; }
        public string nombre_subCat { get; set; }
        public string descrip_subCat { get; set; }
    }
}
